name: OpenSpeedTest
version: v2.0.6
slug: openspeedtest
description: SpeedTest by OpenSpeedTest™ - Free & Open-Source HTML5 Network Performance Estimation Tool.
arch:
  - amd64
  - aarch64
  - armv7
url: https://github.com/openspeedtest/Speed-Test
image: openspeedtest/latest
webui: http://[HOST]:[PORT:3000]/
startup: services
ports:
  3000/tcp: 3000
  3001/tcp: 3001
ports_description:
  3000/tcp: HTTP
  3001/tcp: HTTPS
