name: cell-balance-analyser
version: 0.0.5
slug: cell-balance-analyser
description: Save cell balancing times
arch:
  - amd64
  - aarch64
  - armv7
url: https://github.com/jesseklm/cell-balance-analyser
map:
  - addon_config
options:
  mqtt_server: addon_core_mosquitto
  mqtt_port: 1883
  mqtt_username: user
  mqtt_password: pass
  mqtt_topic: cell-balance-analyser/
  victoriametrics_prom_import_url: http://localhost:8428/api/v1/import/prometheus
  logging: info
schema:
  mqtt_server: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: str
  mqtt_topic: str
  victoriametrics_prom_import_url: str
  logging: list(debug|info|warning|error|critical)
image: ghcr.io/jesseklm/cell-balance-analyser
services:
  - mqtt:need
