name: "sungrowmodbus2mqtt"
version: "master"
slug: "sungrowmodbus2mqtt"
description: "Sungrow Modbus 2 MQTT"
arch:
  - amd64
  - armv7
url: "https://github.com/jesseklm/sungrowmodbus2mqtt"
startup: "services"
boot: "auto"
map:
  - addon_config
image: ghcr.io/jesseklm/sungrowmodbus2mqtt
services:
  - mqtt:need
