name: SungrowModbus2Mqtt-PyPy
version: v1.0.21-pypy
slug: sungrowmodbus2mqtt-pypy
description: Sungrow Modbus 2 MQTT with PyPy
arch:
  - amd64
  - aarch64
  - armv7
url: https://github.com/jesseklm/sungrowmodbus2mqtt
map:
  - addon_config
options:
  mqtt_server: addon_core_mosquitto
  mqtt_port: 1883
  mqtt_username: user
  mqtt_password: pass
  mqtt_topic: sungrowmodbus2mqtt/
  ip: 192.168.0.55
  sungrow_encrypted: false
  logging: info
schema:
  mqtt_server: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: str
  mqtt_topic: str
  ip: str
  sungrow_encrypted: bool
  logging: list(debug|info|warning|error|critical)
image: ghcr.io/jesseklm/sungrowmodbus2mqtt
services:
  - mqtt:need
